# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Alexander Mohr

## set line threshold a bit higher than the default 100
too-many-lines-threshold = 130

## Unwrap is disallowed but accept it in test code
allow-unwrap-in-tests = true
