# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Alexander Mohr

name: PR Lint and Format Checks

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # Grants permission to post review comments

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  format_and_clippy_for_pr:
    runs-on: ubuntu-latest
    name: "PR Lint and Format"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Format and Clippy - Nightly toolchain pinned
        uses: eclipse-opensovd/cicd-workflows/rust-lint-and-format-action@3d52fa5c86094997f8f2d3cb4714f32f6fd23c90
        with:
          toolchain: nightly-2025-07-14
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-format-error: "true"
          fail-on-clippy-error: "true"
          clippy-deny-warnings: "true"
      - name: Format and Clippy - Nightly toolchain latest
        uses: eclipse-opensovd/cicd-workflows/rust-lint-and-format-action@3d52fa5c86094997f8f2d3cb4714f32f6fd23c90
        with:
          toolchain: nightly
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-format-error: "false"
          fail-on-clippy-error: "false"
          clippy-deny-warnings: "false"
