# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Alexander Mohr

name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  PYTHON_VERSION: 3.13
  PRE_COMMIT_VERSION: 4.2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run checks
        uses: eclipse-opensovd/cicd-workflows/pre-commit-action@3d52fa5c86094997f8f2d3cb4714f32f6fd23c90
        with:
          copyright-text: "Alexander Mohr"
          license: "Apache-2.0"
          reuse-template: "mdd_ui"
